apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloapp
spec:
  selector:
    matchLabels:
      app: helloapp
  replicas: 1
  template:
    metadata:
      labels:
        app: helloapp
    spec:
      containers:
      - name: helloapp
        image: 068989220776.dkr.ecr.us-east-1.amazonaws.com/helloapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: helloapp-db
              key: username
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: helloapp-db
              key: password
        - name: DB_HOSTNAME
          valueFrom:
            secretKeyRef:
              name: helloapp-db
              key: hostname

---
apiVersion: v1
kind: Service
metadata:
  name: helloapp-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app: helloapp
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helloapp-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
  labels:
    app: helloapp
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: helloapp-service
              servicePort: 80
